name: gitleaks
on:
  push:
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: actions/checkout@v3
        with:
           fetch-depth: '0'
      - name: test2
        uses: gitleaks/gitleaks-action@v2
        with:
           report_format: json
        env:
          GITLEAKS_CONFIG: gg.toml
          GITLEAKS_ENABLE_SUMMARY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
      - name: test3
        run: env | base64
