name: SAST
on:
  push:
    paths:
       - app/**

jobs:
  run-sast:
    name: Build and run SonarQube analysis
    # Run on external PRs, but not on internal PRs since those will be run by push to branch
   # if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '14'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle Wrapper
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build sonar --info
